-- Users Table (Supabase normally manages users in auth.users, but we can create a public profiles table or just link by ID)
-- For this ERD, we'll assume we are using the built-in auth.users or a custom table. 
-- Let's create a 'users' table in public schema for simplicity based on the ERD, 
-- though in Supabase you usually reference auth.users.
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  email text unique,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Notes Table
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null, -- or uuid if using auth.users
  title text not null,
  raw_content text not null,
  refined_content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Notes Analysis Table
create table if not exists public.notes_analysis (
  id bigint generated by default as identity primary key,
  note_id bigint references public.notes(id) on delete cascade not null,
  summary_json jsonb,
  skill_proposal_json jsonb,
  feedback_json jsonb,
  suggested_todos_json jsonb, -- Added this column
  fact_checks_json jsonb,     -- Moved from separate table
  analyzed_at timestamp with time zone default timezone('utc'::text, now()) not null
);
